### ISSUE TITLE
Template Issue

### ISSUE THREAD

**Issue by bonxz** [cbartel/nw-company-tool#10]
![image](https://user-images.githubusercontent.com/61289944/141686090-60fe6764-7646-40ed-ba2c-a4fbdf18e5b7.png)

You would have to change the width of the column here.

**Comment by bonxz** [comment]
![image](https://user-images.githubusercontent.com/61289944/141695867-c82b5389-c9f5-43de-b613-a96d1410e059.png)
If you show more people, the copyright is behind the template. So it's just a cosmetic flaw.


And it might be good if you could set in the admin settings to always show 50 people by default.

**Comment by cbartel** [comment]
Hi,
I fixed the issue in the current 2.0.0-beta.1 release :) unfortunately there is currently no migration strategy from 1.x to 2.x. as there are a LOT of new things and the database schema is now managed by prisma.io
