### ISSUE TITLE
Expedtiton creation

### ISSUE THREAD

**Issue by bonxz** [cbartel/nw-company-tool#29]
![image](https://user-images.githubusercontent.com/61289944/144123242-915dca2a-a542-499f-bea4-b447a4c6237e.png)

Something is not working with the creation of the expedition. When I fill in everything, I can't press save. I have already logged in again, so that's not the problem.

**Comment by cbartel** [comment]
Hey,
are you on 2.1.0-beta.7 ? I've been having an issue with the prisma client not being updated.
If the issue persists, can you have a look in the server logs?

**Comment by bonxz** [comment]
So now with beta 8 something is not working. I have reinstalled it completely and now I can no longer use the menu. So it is not clickable.
![image](https://user-images.githubusercontent.com/61289944/144287376-37e76d59-3452-4381-87cb-1ad84e939c88.png)

**Comment by cbartel** [comment]
really strange. I've just released beta 9 which contains a hotfix dealing with not being able to login/use the app after wiping the database. But it might not solve that issue. Are there any errors in your Javascript Console (F12) or in the server logs which can put me in the right direction?

**Comment by cbartel** [comment]
ok... I found it - I somehow must have broken the menu, it's not working anymore. Can you still click on your Company Name which should navigate you to "HOME" ?

**Comment by cbartel** [comment]
I fixed the issue with the menu, is everything working for you again? If yes, you can close the issue :)

**Comment by bonxz** [comment]
everthing fixed now :)
