### ISSUE TITLE
How to enable Users? 

### ISSUE THREAD

**Issue by DrugAddict420** [cbartel/nw-company-tool#47]
I´m missing something? How can i enable users? All users who try to use the website, after login with Discord they get redirect to: Disable account page... 

how to manualy enable them? or is bugged? The only user on the administrato panel its me..

**Comment by cbartel** [comment]
Hey,
unfortunately I haven't been running the tool for over a year, so my mind might be a bit fuzzy.

After registering your users should appear in the admin panel. There should be a toggle to enable them.
I guess they need to choose a nickname after authorizing via discord.

A wild guess: can you doublecheck everything regarding discord OAuth2, maybe something is odd there?

Another thing that could help: is the serverlog throwing any errors?

**Comment by DrugAddict420** [comment]
> Hey, unfortunately I haven't been running the tool for over a year, so my mind might be a bit fuzzy.
> 
> After registering your users should appear in the admin panel. There should be a toggle to enable them. I guess they need to choose a nickname after authorizing via discord.
> 
> A wild guess: can you doublecheck everything regarding discord OAuth2, maybe something is odd there?
> 
> Another thing that could help: is the serverlog throwing any errors?

Im gonna try reinstall all.. 

Can i please have your discord? Or can you add at mine? DrugAddict#1051 

I will be happy to buy you few cup coffee if you can help me out <3

**Comment by DrugAddict420** [comment]
@cbartel-ci  Check this:

https://gyazo.com/40d62b445f38d89d019260009d2aa8f7

https://gyazo.com/38d4cc55653654831c5295ad6a4fb501

https://gyazo.com/64f2045b3623568fde47d902042b37da


Where i suppose to enable the user?

**Comment by DrugAddict420** [comment]
@cbartel  @cbartel-ci  You can close the topic. If you have time someday you could add an auto-update.. The solution to show new users in the list, was to use the command stop of pm2 and start it again..

I dont mind to close and start it every time someone need to get approve. But if you can add few lines of code to do an auto-update without restarting the client will be the best! In case you do so i will buy you 2x Coffee <3

**Comment by cbartel** [comment]
Hey buddy,

very strange, wasn't like this the last time I've touched the project. But might ofc be, depending on node version, dependencies and stuff - you never no.

Unfortunately I gave up on this project, will not touch the code in any soon'ish future. But it's here for people to fork and continue :)

closing this issue then :) thanks for your feedback!
