### ISSUE TITLE
Is any chance ?

### ISSUE THREAD

**Issue by DrugAddict420** [cbartel/nw-company-tool#48]
There is any chance you can tell me how to make the website without using your node distribution'? and instead just using the tar.gz release? Please?

**Comment by cbartel** [comment]
Hey,
node is a must for this project, the server only runs on node and was specifically built for it. Without the server backend, you would have a non-functional frontend app which couldn't do anything.

So unfortunately: No, this is not possible.

Have a good day! :)
Cheers
