### ISSUE TITLE
How can i edit the template?

### ISSUE THREAD

**Issue by DrugAddict420** [cbartel/nw-company-tool#49]
Hi, how can i add greatsword and blunderbuss? i need to edit every singular .js file? or is any ez solution? I can implement, but then to edit the template, i need to edit like 7-8 files.. Can you add it or if you check: https://github.com/DrugAddict420/quellopulito

I edit the files and add mutated + blunderbluss and greatsword.. could you add it to your repo? OR what else can i do?

**Comment by cbartel** [comment]
if you have added all the code changes, simply run the following command in the directory:
`npm run build`

this should produce all needed files in the ./dist folder

**Comment by cbartel** [comment]
you can also create a pull request in this repo, I can trigger a release for the changes

**Comment by cbartel** [comment]
oh thats sad, you've created a fork, but didnt use it for the changes
https://github.com/DrugAddict420/nw-guild-cp

if you commit your changes over there, I can pull them into this repo and create a release out of it

**Comment by DrugAddict420** [comment]
@cbartel done i change the files inside: https://github.com/DrugAddict420/nw-guild-cp What now?

**Comment by DrugAddict420** [comment]
Check if everyhing is allright! i did both, edit the forked, and even ask for a pull request! Let me know if is everyhing ok! 
@cbartel-ci

**Comment by cbartel** [comment]
#50 was merged. Thanks for the update. It should now upload the release.. I will check if everything went right. You should be able to use the updater in the admin panel afterwards

**Comment by cbartel** [comment]
as I've feared, I have some authorization issues in the action that uploads the release. Let me get to that quickly, should be done in a few minutes ;)

**Comment by cbartel** [comment]
There was an error building the server

`ERROR in src/expedition/expedition.service.ts:15:10
TS2305: Module '"@prisma/client"' has no exported member 'ExpeditionParticipant'.
    13 |   User,
    14 | } from '@nw-company-tool/model';
  > 15 | import { ExpeditionParticipant } from '@prisma/client';
       |          ^^^^^^^^^^^^^^^^^^^^^
    16 | import { DatabaseClient } from '../database/database.client';
    17 | import { EventService } from '../event/event.service';
    18 |

webpack 5.58.2 compiled with 1 error in 4298 ms`


Need to see, what went wrong there

As I said, this hasn't been touched for a while. These problems occur after not updating for a while :/

**Comment by DrugAddict420** [comment]
@cbartel-ci @cbartel waiting for updates! I got another error, i post in the issue category!

**Comment by DrugAddict420** [comment]
You are the best! Hope you can release asap! If you release tonight i buy you 2 more coffe cuz u deserve it! @cbartel @cbartel-ci

**Comment by cbartel** [comment]
no need ;) it just caught my curiosity .. don't like if things don't work! :)

**Comment by DrugAddict420** [comment]
@cbartel doesnt matter you are helping a lot! You deserve it! Hope you can fix all asap <3

**Comment by cbartel** [comment]
please check if you can get v2.2.3 running without problems, you might have to manually download the node distribution and extract it. Do not delete your data directory :) it should work as before.
If not, you can at least try to rename the database.db file to for example database.db.tmp
In this case, the server will create a fresh database (and your user data will unfortunately be lost)

**Comment by DrugAddict420** [comment]
prisma:info Starting a sqlite pool with 3 connections.
[Nest] 2819  - 02/04/2023, 10:40:09 PM   ERROR [ExceptionsHandler]
Invalid `this.client.user.findUnique()` invocation in
/opt/nwct/nwct-server/dist/server.js:899:33

   896     };
   897 }
   898 async findByDiscordId(discordId) {
→  899     return this.client.user.findUnique(
  The table `main.User` does not exist in the current database.
Error:
Invalid `this.client.user.findUnique()` invocation in
/opt/nwct/nwct-server/dist/server.js:899:33

   896     };
   897 }
   898 async findByDiscordId(discordId) {
→  899     return this.client.user.findUnique(
  The table `main.User` does not exist in the current database.
    at RequestHandler.request (/opt/nwct/nwct-server/node_modules/@prisma/client/runtime/index.js:49022:15)
    at async DatabaseClient._request (/opt/nwct/nwct-server/node_modules/@prisma/client/runtime/index.js:49919:18)
    at async LoginController.callback (/opt/nwct/nwct-server/dist/server.js:1358:26)
    at async /opt/nwct/nwct-server/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /opt/nwct/nwct-server/node_modules/@nestjs/core/router/router-proxy.js:9:17



same error.. im doing something wrong?

**Comment by DrugAddict420** [comment]
whenever im trying to create the first user with discord i get this error.. is some table missing in the db? or is another the problem?


EDIT: Solved in: https://github.com/cbartel/nw-company-tool/issues/51

**Comment by DrugAddict420** [comment]
How can we use https on port 8080? Im reading that we should use 8443.. is that true? Or is another solution to the ssl problem?

**Comment by cbartel** [comment]
hey, i added you at discord. I don't think we should communicate through github issues, as the problems are mainly configuration issues, not code  :)

Closing this issue
