### ISSUE TITLE
ERROR Database

### ISSUE THREAD

**Issue by DrugAddict420** [cbartel/nw-company-tool#51]
prisma:info Starting a sqlite pool with 3 connections.
[Nest] 1893  - 02/04/2023, 7:38:42 PM   ERROR [ExceptionsHandler]
Invalid `this.client.user.findUnique()` invocation in
/opt/nwct/nwct-server/dist/server.js:816:33

   813     };
   814 }
   815 async findByDiscordId(discordId) {
→  816     return this.client.user.findUnique(
  The table `main.User` does not exist in the current database.
Error:
Invalid `this.client.user.findUnique()` invocation in
/opt/nwct/nwct-server/dist/server.js:816:33

   813     };
   814 }
   815 async findByDiscordId(discordId) {
→  816     return this.client.user.findUnique(
  The table `main.User` does not exist in the current database.
    at RequestHandler.request (/opt/nwct/nwct-server/node_modules/@prisma/client/runtime/index.js:49022:15)
    at async DatabaseClient._request (/opt/nwct/nwct-server/node_modules/@prisma/client/runtime/index.js:49919:18)
    at async LoginController.callback (/opt/nwct/nwct-server/dist/server.js:1275:26)
    at async /opt/nwct/nwct-server/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /opt/nwct/nwct-server/node_modules/@nestjs/core/router/router-proxy.js:9:17
[Nest] 1893  - 02/04/2023, 7:38:42 PM   ERROR [ExceptionsHandler]
Invalid `this.client.user.findUnique()` invocation in
/opt/nwct/nwct-server/dist/server.js:816:33

   813     };
   814 }
   815 async findByDiscordId(discordId) {
→  816     return this.client.user.findUnique(
  The table `main.User` does not exist in the current database.
Error:
Invalid `this.client.user.findUnique()` invocation in
/opt/nwct/nwct-server/dist/server.js:816:33

   813     };
   814 }
   815 async findByDiscordId(discordId) {
→  816     return this.client.user.findUnique(
  The table `main.User` does not exist in the current database.
    at RequestHandler.request (/opt/nwct/nwct-server/node_modules/@prisma/client/runtime/index.js:49022:15)
    at async DatabaseClient._request (/opt/nwct/nwct-server/node_modules/@prisma/client/runtime/index.js:49919:18)
    at async LoginController.callback (/opt/nwct/nwct-server/dist/server.js:1275:26)
    at async /opt/nwct/nwct-server/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /opt/nwct/nwct-server/node_modules/@nestjs/core/router/router-proxy.js:9:17

Why i get this?

**Comment by DrugAddict420** [comment]
@cbartel @cbartel-ci  did you delete a table in the database?

**Comment by cbartel** [comment]
hey,

can't tell why this happened. Might be due to the update... we didn't do proper testing ;)
Can you try with a fresh database if the error persists?

I got v2.2.3 running on my local machine without any problems

**Comment by DrugAddict420** [comment]
This issue happen because of misconfiguration of port or ip andress. if someone happen to have the same issue check ur config file in data folder!

Im gonna close the issue as solved.
