### ISSUE TITLE
something is off.. with ssl

### ISSUE THREAD

**Issue by DrugAddict420** [cbartel/nw-company-tool#52]
The database error is because of proxy configuration.. now everything seems to work, the only problem i get a infinite redirect and crash with 0 errors when try to access the callback from discord.. 

without ssl everything should work, i will try again after.. but with ssl doesnt work.. 
i need to config everything with :8080 otherwise i get database proxy error..

try urself you cant register: https://nwct.nwguild.eu/

code snippet: https://snappify.com/view/19685c8e-64e9-4c81-934b-a38844a9b68e

discord dev page link + image: 
https://nwct.nwguild.eu:8080/api/login/callback

`https://gyazo.com/368f814564faf5dbf5d0e6a41b0d2313`

Tell me if you need something else! 

what im doing wrong?

**Comment by DrugAddict420** [comment]
Basicaly without ssl everything work fine.. but if i put ssl i got errors like: 

 SSL_ERROR_RX_RECORD_TOO_LONG
 
 Why i cant install ssl? On normal website there is ssl, but on port 8080 is not working... how to fix @cbartel  @cbartel-ci  ?

**Comment by cbartel** [comment]
Ok, there seems to be something odd...

It should work the following:

a) the process is running on http://localhost:8080, no SSL, no nothing
b) nginx will accept reqeuests at port 443 (https), do all stuff related to SSL and then forward the request to http://localhost:8080

therefore you dont need to specify port 8080 at discord. At best, don't open your firewall for port 8080, only make port 80 and 443 available to public


Here is how your nginx config should look like before using certbot
```
server {

    # replace with your domain
    server_name             nwct.nwguild.eu;

    # Listen on port 80 without SSL certificates, we will deal with https later
    listen                  80;

    # Sets the Max Upload size to 300 MB
    client_max_body_size 300M;

    # Proxy Requests to NWCT
    location / {

        # Set proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # These are important to support WebSockets
        # WebSockets are currently not used in NWCT, but are planned in future releases.
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        # Here we tell nginx to forward all request to localhost on port 8080
        proxy_pass http://localhost:8080;
    }
}
```

now run
```
# Create a link in sites-enabled to enable your proxy
sudo ln -s /etc/nginx/sites-available/nwct /etc/nginx/sites-enabled

# Test your nginx config
sudo service nginx configtest

# Restart Nginx
sudo service nginx restart
```

also check your config
```
cd /opt/nwct/nwct-data
nano config.json
```

it should have
```
"BASE_URL": "http://nwct.nwguild.eu",
```

This should make your instance available to public through the standard http port
http://nwct.nwguild.eu <-- NO port 8080, if this is not working, there is already something odd

configure your discord OAuth to use `http://nwct.nwguild.eu/api/login/callback` <-- NO https yet, just plain old http



if that works, run certbot
```
sudo certbot --nginx
```

do all the stuff it asks you for.

Afterwards, you need to configure discord OAuth to use `https://nwct.nwguild.eu/api/login/callback`
and change in your config.json
```
"BASE_URL": "https://nwct.nwguild.eu",
```

that should be it, not much magic about it. It seems like you got a bit confused with all the ports and stuff.

Hope that helps somehow ;)

**Comment by DrugAddict420** [comment]
If someone happen to have the same error this are the possible solution:

- Wait 48h for DNS propagation
- Do not use DigitalOcean domain tool, and use instead manual configuration on your subdomain of ur choice. 
- Reinstall ssl certificates and setup everything for another subdomain! 
- Reinstall ubuntu and re-setup everything


im closing the issue as solved!
